[project]
name = "randalf"
version = "0.1.0"
description = "Environment and secret manager"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "PyYAML",
]

[project.scripts]
randalf = "randalf.__main__:main"
